#!/bin/sh /etc/rc.common

START=97
boot() {
. /lib/functions.sh

case $(board_name) in
	linksys,panamera)
		# clear partialboots and always set to boot first partition
		nvram set bootpartition=0 && nvram set partialboots=0 && nvram commit
		;;
esac
}
